### ISSUE TITLE
Temporal inference

### ISSUE THREAD

**Issue by BaoWentz** [linxuewu/Sparse4D#12]
Can we futher improve mAP or NDS of valset and testset, if we use temporal information during inference?Thanks!

**Comment by linxuewu** [comment]
Which specific temporal information are you referring to?

**Comment by BaoWentz** [comment]
https://github.com/linxuewu/Sparse4D/blob/c48ecd2b020d7770faaa865f577eed28406b75e9/projects/configs/sparse4d_r101_H4.py#L24
During test time, we set seq_frame=0 by default, so we won't use temporal keypoint information.

**Comment by linxuewu** [comment]
During inference, instead of using multi-frame sampling, we employed sequential reasoning and stored the features of historical frames in the head. Therefore, we utilized temporal information in our approach.

**Comment by linxuewu** [comment]
https://github.com/linxuewu/Sparse4D/blob/main/projects/mmdet3d_plugin/models/sparse4d_head.py#L171

**Comment by BaoWentz** [comment]
I got it, thanks for your reply.
