### ISSUE TITLE
How to get valid output?

### ISSUE THREAD

**Issue by BaoWentz** [linxuewu/Sparse4D#13]
https://github.com/linxuewu/Sparse4D/blob/c48ecd2b020d7770faaa865f577eed28406b75e9/projects/mmdet3d_plugin/models/decoder.py#L15
In inference stage, we will get 900 anchors and after post_process we finally get 300 anchors. However most of these anchors will be FP, so how to get good predicts?Can we set score_threshold=0.5 to simply get what we want?Thanks!

**Comment by linxuewu** [comment]
Of course, you can set a threshold to reduce fp and obtain more reliable results for downstream tasks to use. We are here to calculate mAP, so there is no threshold set.  The score_threshold for our video demo is 0.35. https://github.com/linxuewu/Sparse4D/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py#L121

**Comment by BaoWentz** [comment]
Thanks!
