### ISSUE TITLE
Code Organization and Cleanup

### ISSUE THREAD

**Issue by linxuewu** [linxuewu/Sparse4D#16]
The current state of the codebase is not well-organized and requires further cleanup. This issue aims to address the lack of clarity in the code structure and improve its overall cleanliness. While the code may still have some unresolved issues, your feedback is greatly appreciated, and I will make every effort to assist in resolving them. Rest assured, the code's cleanliness will continue to improve over time.

**Comment by BaoWentz** [comment]
https://github.com/linxuewu/Sparse4D/blob/9a0de41e3f5bd43f02e0b580c85cd1db84f51837/projects/mmdet3d_plugin/models/detection3d/detection3d_blocks.py#L99

**Comment by jasonkhadka** [comment]
Documentation on data perparation and data preparation script.

**Comment by linxuewu** [comment]
> Documentation on data perparation and data preparation script.

You can use the [mmdet3d data converter script](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0rc0/tools/data_converter/nuscenes_converter.py) to generate the pkl files.
