### ISSUE TITLE
How can we prepare nuscenes_infos_train.pkl ?

### ISSUE THREAD

**Issue by zzningxp** [linxuewu/Sparse4D#18]
nuscenes_cam
│   │   ├── nuscenes_infos_test.pkl
│   │   ├── nuscenes_infos_train.pkl
│   │   ├── nuscenes_infos_val.pkl
│   │   └── nuscenes_infos_trainval_with_inds.pkl

Trainval_with_inds is valid at: https://github.com/linxuewu/Sparse4D/releases/download/v0.0/nuscenes_infos_trainval_with_inds.pkl
Train is valid at: https://github.com/linxuewu/Sparse4D/releases/download/v0.0/nuscenes_infos_train.pkl. BUT, mmcv load this pkl will encounter a problem: 
```
File "/opt/miniconda3/envs/py38k/lib/python3.8/site-packages/mmcv/fileio/io.py", line 57, in load
raise TypeError(f'Unsupported format: {file_format}') 
```
Val is not valid at the web url.

Furthermore, can we prepare pkl files myself ?

**Comment by linxuewu** [comment]
1. We don't upload the val pickle yet.
2. You can prepare the pkl file by mmdet3d/tools/data_converter/nuscenes_converter.py, where the version of mmdet3d >= 1.0.0rc0.

**Comment by linxuewu** [comment]
The val pickle is uploaded just now.
https://github.com/linxuewu/Sparse4D/releases/download/v0.0/nuscenes_infos_val.pkl

**Comment by zzningxp** [comment]
Why nuscenes_infos_train.pkl file encounter the mmcv load problem ?

**Comment by linxuewu** [comment]
We have not encountered this situation, check the version of mmcv first？

**Comment by zzningxp** [comment]
What is your python version ?

**Comment by linxuewu** [comment]
3.6.8

**Comment by zzningxp** [comment]
My env is python 3.8 torch '1.13.1+cu117' mmcv-full==1.6.0 mmdetection3d v1.0.0rc6.
The versions are too different, letme check out to your version.

**Comment by wst20000804** [comment]
你好请问可以上传下迷你版本的pkl吗？
