### ISSUE TITLE
Regarding ablation study for motion compensation

### ISSUE THREAD

**Issue by thom966** [linxuewu/Sparse4D#2]
Hello, thank you for your great work.

I am writing this issue to ask about the ablation study conducted on ego motion and object motion.
I believe that ego motion compensation follows similar process as BEVDet and BEVDepth, which aligns past frame _t_ to current frame _t_0_.
![image](https://user-images.githubusercontent.com/84850569/207243890-486f209d-fe88-4366-b9b1-bc229750dd33.png)

For object motion compensation, I think it follows the equation 4 in the paper: ![image](https://user-images.githubusercontent.com/84850569/207242804-33565e1e-b16a-4b5b-ba09-81914d192587.png) .

And my question is how is it possible to conduct both ego and object motion compensation at the same time as in the last row of Table 2?
![image](https://user-images.githubusercontent.com/84850569/207243623-96bd74fa-ee15-48e6-87b2-56e37a428b2c.png)

Thank you for your reply in advance.

**Comment by linxuewu** [comment]
1. Unlike bevdet and bevdepth, we perform motion compensation on keypoints rather than the entire BEV feature.
