### ISSUE TITLE
Problem about tracking

### ISSUE THREAD

**Issue by JunqiaoLi** [linxuewu/Sparse4D#20]
Thank you for your great work!
I wonder if you have released the code related to tracking, since the 'tracking for NuScenes3DDetTrackDataset' is False for all configs.

If you have released it, is there an example config?

**Comment by linxuewu** [comment]
The dataset supports tracking evaluation, but the code of the multi-object tracking model has not been released yet.

Our previous tracking method was implemented by post-processing of feature similarity matching, but we have given up exploring this method. 

We will directly expose the model for joint detection and tracking later.

**Comment by JunqiaoLi** [comment]
> The dataset supports tracking evaluation, but the code of the multi-object tracking model has not been released yet.
> 
> Our previous tracking method was implemented by post-processing of feature similarity matching, but we have given up exploring this method.
> 
> We will directly expose the model for joint detection and tracking later.

Thank you for your reply! May I know when you are going to release the joint detection-tracking code?

**Comment by linxuewu** [comment]
The time is still uncertain, and it won't be soon, at least 1-2 months later.
