### ISSUE TITLE
How to generate nuscenes_infos_train.pkl and nuscenes_kmeans900.npy

### ISSUE THREAD

**Issue by desenzhou** [linxuewu/Sparse4D#22]
Hi, I'm fresh to nuscenes. I am just curious about how to generate the nuscenes_infos_train.pkl, nuscenes_infos_val.pkl, etc. Is there any difference bettween them and the nuscenes2d_temporal_infos_train.pkl in [StreamPETR](https://github.com/exiawsh/StreamPETR/blob/main/docs/data_preparation.md)?

Btw, could you provide the script about how to generate nuscenes_kmeans900.npy, thanks so much!

**Comment by linxuewu** [comment]
You can use the [mmdet3d data converter script](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0rc0/tools/data_converter/nuscenes_converter.py) to generate the pkl files. 
The x/y/z in the anchor file is obtained by clustering the center point of the gt box of the nuscenes train dataset, and the other h/w/l/yaw/velo are set to a fixed value.
In addition, we provide ready-made data pkl files and anchor npy file that can be used, see https://github.com/linxuewu/Sparse4D/releases/tag/v0.0.

**Comment by linxuewu** [comment]
You can use sklearn.cluster.KMeans in the python to cluster and generate anchor.npy.
