### ISSUE TITLE
Feature instances not learned parameters?

### ISSUE THREAD

**Issue by jasonkhadka** [linxuewu/Sparse4D#25]
Hi, 
The grads are turned off for instance features. How are they updated?

https://github.com/linxuewu/Sparse4D/blob/fec3a5ea673034a15a2502b0195e3611ae5c7298/projects/configs/sparse4dv2_r50_HInf_256x704.py#L117

**Comment by linxuewu** [comment]
We initialize instance features as all zeros and fix their gradients, preventing them from being updated during training. This approach performs slightly better than using random initialization followed by gradient updates.

> Hi, The grads are turned off for instance features. How are they updated?
> 
> https://github.com/linxuewu/Sparse4D/blob/fec3a5ea673034a15a2502b0195e3611ae5c7298/projects/configs/sparse4dv2_r50_HInf_256x704.py#L117

**Comment by jasonkhadka** [comment]
How are instance features then learned?

**Comment by linxuewu** [comment]
The initial layer's instance features do not need to be learnable.

**Comment by jasonkhadka** [comment]
Can you explain bit more? How and where are instance features encoded then?

**Comment by linxuewu** [comment]
Instance features primarily stem from the image feature map, obtaining meaningful information through deformable aggregation.

> Can you explain bit more? How and where are instance features encoded then?
