### ISSUE TITLE
Where is nuscenes_kmeans900.npy?

### ISSUE THREAD

**Issue by cgl-cell** [linxuewu/Sparse4D#33]
I can't find it. Thank you

**Comment by linxuewu** [comment]
https://github.com/linxuewu/Sparse4D/releases/download/v0.0/nuscenes_kmeans900.npy

**Comment by linxuewu** [comment]
All links provided for downloading files are here. https://github.com/linxuewu/Sparse4D/releases/tag/v0.0

**Comment by cgl-cell** [comment]
> All links provided for downloading files are here. https://github.com/linxuewu/Sparse4D/releases/tag/v0.0

OK, thank you so much for the excellent work you do!

**Comment by dlutguobin** [comment]
how to generate nuscenes_kmeans900.npy? Is there any python script?

**Comment by linxuewu** [comment]
> how to generate nuscenes_kmeans900.npy? Is there any python script?

We do not provide the script for anchor kmeans. You can use `sklearn.cluster.KMeans` to cluster the center points of the gt boxes, then set `w h l yaw vx vy vz`  ​​to fixed values, refer to the [anchor file](https://github.com/linxuewu/Sparse4D/releases/download/v0.0/nuscenes_kmeans900.npy)

**Comment by jesslyn1999** [comment]
Hi, super great work, and thanks for the explanation! I still have a question. `w h l yaw vx vy vz` is set to fixed values, but objects with different classes have different values of those properties. Can you help to give more insights? thanks
