### ISSUE TITLE
关于InfiniteGroupEachSampleInBatchSampler

### ISSUE THREAD

**Issue by shaoqb** [linxuewu/Sparse4D#35]
我理解InfiniteGroupEachSampleInBatchSampler 是每个batch单独跑一个stream/clip？在两个clip交界的时候， 请问怎么处理第一帧的，第一帧并没有上一帧进行叠帧。训练的时候哪里进行判断第一帧

**Comment by linxuewu** [comment]
每个batch中的数据是不同clip，不同batch中的同一batch_index来自同一clip。两个clip的交界处，在model里面用time_interval>2s的方式处理了。
