### ISSUE TITLE
V3的centerness和yawness

### ISSUE THREAD

**Issue by zhhy1999** [linxuewu/Sparse4D#37]
Hi xuewu，
Sparse4D v3中关于yawness和centerness的训练的Y_pred和C_pred具体是？
<img width="770" alt="v3" src="https://github.com/linxuewu/Sparse4D/assets/151845354/1bc81910-4ee2-496d-8950-f2a8deaa5e87">

**Comment by linxuewu** [comment]
Y_pred和C_pred是网络的输出的两个值，和confidence socres类似。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月23日(周四) 晚上8:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [linxuewu/Sparse4D] V3的centerness和yawness (Issue #37)




 
Hi xuewu，
 Sparse4D v3中关于yawness和centerness的训练的Y_pred和C_pred具体是？

**Comment by zhhy1999** [comment]
就是模型预测的yawness值，它的target是<img width="368" alt="image" src="https://github.com/linxuewu/Sparse4D/assets/151845354/c454c25c-7103-4b2d-b5da-e5c8343e4da9">？

**Comment by linxuewu** [comment]
是的，公式(3)和(4)是C_pred和Y_pred的target，这两个target和模型预测的box相关。

**Comment by zhhy1999** [comment]
谢谢~
