### ISSUE TITLE
初始anchor

### ISSUE THREAD

**Issue by sidiangongyuan** [linxuewu/Sparse4D#40]
初始的通过聚类得到的anchor有什么好处？  可以随机初始化吗？

**Comment by linxuewu** [comment]
anchor的初始化方式影响不大，采用均匀初始化和k-means效果差不多。

**Comment by sidiangongyuan** [comment]
谢谢，可以再问一下v1的python版本是多少？ 在编译完cuda算子之后，导入.so文件，一直显示找不到模块

**Comment by linxuewu** [comment]
我这边python3.6和python3.8都能跑。能把完整报错贴上来么？

**Comment by sidiangongyuan** [comment]
> 我这边python3.6和python3.8都能跑。能把完整报错贴上来么？

谢谢，我已经解决了这个问题。python3.8可以正常运行。 应该是编译器无法识别.so ，不影响运行
