### ISSUE TITLE
在训练过程是如何控制时序输入前后顺序的？

### ISSUE THREAD

**Issue by pengcheng001** [linxuewu/Sparse4D#42]
感谢你非常棒的工作，看了你的代码后有一些疑惑请教你一下：
在V2版本中，训练过程中，instance_bank会在训练迭代的过程训练缓存当前的feature和anchor，训练集是按照sense划分的，整个数据集的数据不是连续的，如何保证从instance_bank获取的cache的feature和anchor与当前batch数据的连贯性呢？

谢谢！！！

**Comment by linxuewu** [comment]
通过[batch_in_group_sampler](https://github.com/linxuewu/Sparse4D/blob/main/projects/mmdet3d_plugin/datasets/samplers/infinite_group_each_sample_in_batch_sampler.py#L46)控制训练数据的顺序，然后在model中会用[max_time_interval](https://github.com/linxuewu/Sparse4D/blob/main/projects/mmdet3d_plugin/models/instance_bank.py#L38)去判断样本是否来自新的scene。
