### ISSUE TITLE
关于深度

### ISSUE THREAD

**Issue by WangYichen222** [linxuewu/Sparse4D#46]
作者您好，很感谢您出色的工作，我想请教一下是否有关注过该算法输出的预测框在深度上的误差？另外v2版本中增加了深度的监督后，深度是否更加准确呢？

**Comment by linxuewu** [comment]
我没有直接测过深度上的误差，目前只能从mATE这个指标看框的精度。
加深度监督，对比加DN做辅助监督，并没有观察到的mATE有明显改善。

**Comment by linxuewu** [comment]
深度是否准，其实不只由回归分支决定，受分类分支也非常大。因为同ray下会出现很多重叠框，分类准确就代表ray下的分布估计合理，也就会使得感知结果深度准确。

**Comment by WangYichen222** [comment]
感谢分享！
