### ISSUE TITLE
Inquiries about ckpt files learned by VoVNet and ResNet-101 backbone on the Sparse4Dv2

### ISSUE THREAD

**Issue by altkddhfcjs** [linxuewu/Sparse4D#47]
Hello, I am impressed with your papers.

I can check to provide only the config setting and model trained files for ResNet50 in Sparse4D v2.
So, can I get config files and ckpt files for ResNet-101 and VoVNet-99 for Sparse4D v2??

Additionally, I look forward to the Sparse4D v3 released.
Thank you!

**Comment by linxuewu** [comment]
checkpoint: [resnet101 ImageNet](https://download.pytorch.org/models/resnet101-5d3b4d8f.pth), [resnet101 nuImage](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/nuimages_semseg/cascade_mask_rcnn_r101_fpn_1x_nuim/cascade_mask_rcnn_r101_fpn_1x_nuim_20201024_134804-45215b1e.pth), [VoVNet DD3D](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/nuimages_semseg/cascade_mask_rcnn_r101_fpn_1x_nuim/cascade_mask_rcnn_r101_fpn_1x_nuim_20201024_134804-45215b1e.pth)

**Comment by linxuewu** [comment]
Configs other than resnet50 are not planned to be released.


I have finished organizing the code of sparse4d v3 and am going through the company approval process. It will be released soon

**Comment by altkddhfcjs** [comment]
Thank you for your comments!
