### ISSUE TITLE
When will sparse4d v3 be released ?

### ISSUE THREAD

**Issue by Xiang95** [linxuewu/Sparse4D#48]
can't wait to try this SOTA Algorithm out XD

**Comment by linxuewu** [comment]
Code of sparse4dv3 will be released soon, and it has been organized and is awaiting company approval. It is estimated to take about one week.


> can't wait to try this SOTA Algorithm out XD

**Comment by Xiang95** [comment]
> Code of sparse4dv3 will be released soon, and it has been organized and is awaiting company approval. It is estimated to take about one week.
> 
> > can't wait to try this SOTA Algorithm out XD
thank you for ur quick reply and great to hear this exiciting news!

**Comment by Xiang95** [comment]
> Thank you for ur quick reply and great to hear this exiciting news!
>> Code of sparse4dv3 will be released soon, and it has been organized and is awaiting company approval. It is estimated to take about one week.
> 
> > > can't wait to try this SOTA Algorithm out XD

**Comment by linxuewu** [comment]
【2024/01/22】The code repository for Sparse4D has been migrated to [HorizonRobotics/Sparse4D](https://github.com/HorizonRobotics/Sparse4D/tree/main), and the code for Sparse4Dv3 has also been open-sourced in the new code repository!!! Everyone is welcome to use it.
