### ISSUE TITLE
Will the noramalize_yaw be helpful?

### ISSUE THREAD

**Issue by WeijieMax** [linxuewu/Sparse4D#5]
Will the hyperparameter noramalize_yaw in the refine module be helpful to pred sin & cos?

**Comment by linxuewu** [comment]
This doesn't bring metrics boost, so I didn't turn it on.

**Comment by WeijieMax** [comment]
Thanks a lot for your instant reply. By the way, I saw you substitute the traditional positional embedding with the anchor embedding, did this help a lot?

**Comment by linxuewu** [comment]
Positional embeddings from the box3d encoder will give a 2% NDS boost over stochastically learnable positional embeddings(like detr3d).  We think this approach is more helpful for decoupling image features and anchor structured feature(position embeding).

**Comment by WeijieMax** [comment]
Oh, such a high increase the approach brought, and I also truly agree with the revision. Thanks for your patient reply.
