### ISSUE TITLE
【关于DenseDepthNet】如何设计密集深度预测的监督方式？

### ISSUE THREAD

**Issue by LuckySunnye** [linxuewu/Sparse4D#50]
您好，请问Sparse4Dv2代码中，
1. 为什么DenseDepthNet模块使用回归任务来做监督，而不是普通使用的分类任务？
2. 回归损失函数为何这样设计，分母为什么是len(gt) * len(depth_preds) ？ 
在我的模型里，error = torch.abs(depth_preds - gt_depths).sum()，error的值是338249.6469， 而分母 len(gt_depths) * len(depth_preds)的值是 30220*30220=913248400；使得最终得到的loss=338249.6469 / 913248400 = 0.00037038077143086153;这个值非常的小，同时乘以0.2的loss_weight以后就更小了，所以想问一下，这个depth_loss是否是符合预期的呢？

非常感谢~！

**Comment by linxuewu** [comment]
1.  深度估计，回归也挺常用的。只是用来做辅助监督，图省事就用了回归 ，你也可试试分类。
  2.  len(depth_preds)=3，因为depth_preds是个list[tensor]。

________________________________
发件人: LuckySunnye ***@***.***>
发送时间: 2024年1月17日 22:29:14
收件人: linxuewu/Sparse4D
抄送: Subscribed
主题: [linxuewu/Sparse4D] 【关于DenseDepthNet】如何设计密集深度预测的监督方式？ (Issue #50)


谨慎:

这是一个来自外部的邮件，如果邮件中包含链接或附件等可能的风险因素，在操作之前请确保发件人可信，如不确认发件人可信，请联系邮件管理员。


您好，请问Sparse4Dv2代码中，

  1.  为什么DenseDepthNet模块使用回归任务来做监督，而不是普通使用的分类任务？
  2.  回归损失函数为何这样设计，分母为什么是len(gt) * len(depth_preds) ？
在我的模型里，error = torch.abs(depth_preds - gt_depths).sum()，error的值是338249.6469， 而分母 len(gt_depths) * len(depth_preds)的值是 30220*30220=913248400；使得最终得到的loss=338249.6469 / 913248400 = 0.00037038077143086153;这个值非常的小，同时乘以0.2的loss_weight以后就更小了，所以想问一下，这个depth_loss是否是符合预期的呢？

非常感谢~！

―

**Comment by LuckySunnye** [comment]
啊。。原来len(depth_preds)=3。。 多谢多谢~
