### ISSUE TITLE
您好，我在复现您的工作的时候，出现了NuScenes3DDetTrackDataset Not Found的问题

### ISSUE THREAD

**Issue by tyloocifer** [linxuewu/Sparse4D#51]
这是因为MMdet3D plugin中的插件没有注册成功吗，我应该如何解决。而且我能否使用Nuscenes的v1.0mini数据集进行实验？我应该在哪些部分进行更改？谢谢您！！

**Comment by linxuewu** [comment]
先检查config中是否正确设置

**Comment by linxuewu** [comment]
可以用mini进行debug，把这个pkl文件改为mini的就行。

https://github.com/linxuewu/Sparse4D/blob/main/projects/configs/sparse4dv2_r50_HInf_256x704.py#L335

**Comment by llllCHYllll** [comment]
@tyloocifer 这是环境配置问题，mmdetection3d的版本有错误，可以跟着这个docker file配环境，一步步下来可以稳定运行：[https://hub.docker.com/layers/eagleflag/sparse4d/v001/images/sha256-f3885109d7f5d7434c71e4497afd84a82de2c876563018c15ad87c9b1942c669?context=explore](url)
