### ISSUE TITLE
Why is learning rate in R50 logs half of the config lr?

### ISSUE THREAD

**Issue by NaomiEX** [linxuewu/Sparse4D#53]
When looking at your R50 logs and configs, I noticed that the lr in the logs is 3e-4 after warmup:
![image](https://github.com/linxuewu/Sparse4D/assets/54797931/a0f9386a-5943-45f6-a4b9-ec7c22d84a77)

whereas in the config the lr should be 6e-4:
![image](https://github.com/linxuewu/Sparse4D/assets/54797931/4b1c5c1b-8971-4614-931c-02d59b815623)

Is this the intended behaviour? This doesn't show up in the R101 config and I was wondering why it behaves like this

**Comment by NaomiEX** [comment]
Nevermind, it turns out that the TextLoggerHook prints out the lr of the first param group, which happens to be the img_backbone in this case, and its lr is halved.

**Comment by linxuewu** [comment]
> Nevermind, it turns out that the TextLoggerHook prints out the lr of the first param group, which happens to be the img_backbone in this case, and its lr is halved.
> 
> Although as a suggestion to the authors, you could change the order of param groups, like create self.head or self.neck first in sparse4d.py instead of self.img_backbone to avoid this confusion as I spent an hour trying to figure out why my lr was getting halved

This is a design flaw in mmcv, changing the model order cannot fundamentally solve the problem, for example, when lr scale is also set for the head or neck.
