### ISSUE TITLE
关于速度预测逻辑

### ISSUE THREAD

**Issue by martinchen0776** [linxuewu/Sparse4D#60]
‘’‘
        if self.output_dim > 8:
            if not isinstance(time_interval, torch.Tensor):
                time_interval = instance_feature.new_tensor(time_interval)
            translation = torch.transpose(output[..., VX:], 0, -1)
            velocity = torch.transpose(translation / time_interval, 0, -1)
            output[..., VX:] = velocity + anchor[..., VX:]
’‘’
您好，在解码速度时通过residual不断相加，并在decoder中refine，这地方的逻辑不太明白？

**Comment by linxuewu** [comment]
网络输出当前帧和上一帧目标位移的残差，这个残差除以时间间隔得到速度的残差，用来refine 速度。

**Comment by martinchen0776** [comment]
感谢！
