### ISSUE TITLE
目标运动补偿的问题请教

### ISSUE THREAD

**Issue by 2anchao** [linxuewu/Sparse4D#65]
作者你好：
     感觉论文的idea和代码都写的非常好，但有个目标的运动补偿的代码我不太理解。

-             if src_timestamp is not None and dst_timestamps is not None:
                translation = vel.transpose(0, -1) * (
                    src_timestamp - dst_timestamps[i]
                ).to(dtype=vel.dtype)
                translation = translation.transpose(0, -1)
                center = center - translation
            dst_anchor[..., [X, Y, Z]] = (
                torch.matmul(
                    T_src2dst[..., :3, :3], center[..., None]
                ).squeeze(dim=-1)
                + T_src2dst[..., :3, 3]
            )

这里的vel是学习的绝对速度是嘛，我看nuscenes是在全局坐标系下计算的速度。那是不是应该先将center转到全局坐标系后再减去translation，而不是再ego坐标系下的center减去全局的translation呢

**Comment by yushengjiexy** [comment]
hi，@2an 你最后是怎么解决的
